warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: warehouse
      port: 5432
      user: postgres
      password: postgres
      dbname: warehouse
      schema: public
      threads: 4
